### Register a new user
POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "usjadon19@gmail.com"
}



### Send notifications to users
POST http://localhost:3000/notification/send-notifications HTTP/1.1
Content-Type: application/json

{
  "users": ["usjadon19@gmail.com"],
  "template": "Hello, {name}! You have {notifications_count} new notifications.",
  "dataMap": {
    "name": "John Doe",
    "notifications_count": 5
  }
}


###