### GET request to example server
POST http://localhost:3000/publisher/send-notifications HTTP/1.1
Content-Type: application/json

{
  "users": ["usjadon19@gmail.com", "user2@example.com"],
  "template": "Hello, {name}! You have {notifications_count} new notifications.",
  "dataMap": {
    "name": "John Doe",
    "notifications_count": 5
  }
}


###